#!/usr/bin/python

#----------------------------------------------------------------------
#
# $Id$
#
# Create tables for GeneticsProfessional emailer information.
#
# BZIssue::4630
#
#----------------------------------------------------------------------
import util

#----------------------------------------------------------------------
# Connect to the database.
#----------------------------------------------------------------------
conn = util.getConnection()
cursor = conn.cursor()

#----------------------------------------------------------------------
# Clear out the tables if they already exist.
#----------------------------------------------------------------------
try:
    cursor.execute('DROP TABLE emailers.gp_emailer')
    conn.commit()
    print "emailers.gp_emailer table dropped"
except:
    pass
try:
    cursor.execute('DROP TABLE dropbox.gp_emailer_job')
    conn.commit()
    print "dropbox.gp_emailer_job table dropped"
except:
    pass

#----------------------------------------------------------------------
# One row for a set of emailer batches generated at the same time.
#
#           id: primary key (derived from CDR emailer pub job ID)
#     emailers: compressed XML document containing info for emailers
#  mailer_type: which type of mailer (e.g., Genetics Professional-Initial)
#     uploaded: date/time job was uploaded by the CDR server
#     imported: date/time job was imported into the emailers database
#----------------------------------------------------------------------
cursor.execute("""\
 CREATE TABLE dropbox.gp_emailer_job
          (id INTEGER      NOT NULL PRIMARY KEY,
     emailers MEDIUMBLOB   NOT NULL,
  mailer_type VARCHAR(128) NOT NULL,
     uploaded DATETIME     NOT NULL,
     imported DATETIME         NULL,
lookup_values MEDIUMBLOB   NOT NULL)
      ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci""")
conn.commit()
print "dropbox.gp_emailer_job table created"

#----------------------------------------------------------------------
# One row for each emailer document.
#
#        id: primary key (matches CDR ID for mailer tracking document)
#    cdr_id: CDR ID for repository document behind mailer document
#       job: emailer job to which this emailer belongs
#     email: address to which the emailer message was sent
#      name: name of genetics professional (extracted from original XML)
#       xml: current XML document
#  original: original XML document
#    mailed: when the emailer notification went out
#   bounced: when we learned that the mailer was undeliverable
# completed: when the recipient responded
#----------------------------------------------------------------------
cursor.execute("""\
CREATE TABLE emailers.gp_emailer
         (id INTEGER      NOT NULL PRIMARY KEY,
      cdr_id INTEGER      NOT NULL,
         job INTEGER      NOT NULL REFERENCES dropbox.gp_emailer_job,
       email VARCHAR(128) NOT NULL,
        name VARCHAR(256) NOT NULL,
         xml MEDIUMTEXT   NOT NULL,
    original MEDIUMTEXT   NOT NULL,
      mailed DATETIME         NULL,
     bounced DATETIME         NULL,
   completed DATETIME         NULL)
      ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci""")
conn.commit()
print "emailers.gp_emailer table created"
